---

- name: CLICKHOUSE | Add configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ clickhouse_config_directory }}/{{ item }}"
    mode: 0644
  with_items: "{{ clickhouse_config_files }}"
  notify: "{{ clickhouse_handler_on_config_change }}"
  tags: config_files
