---

- name: CLICKHOUSE | Ensure clickhouse group
  group:
    name: "{{ clickhouse_group }}"
    system: yes
    state: present

- name: CLICKHOUSE | Ensure clickhouse user
  user:
    name: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    system: yes
    shell: /usr/sbin/nologin
    createhome: no

- name: CLICKHOUSE | Update repositories cache and install apt-transport-https, dirmngr packages
  apt:
    name: "{{ clickhouse_prerequisite_repos }}"
    state: present

- name: CLICKHOUSE | Be sure key is present
  apt_key:
    keyserver: "{{ clickhouse_deb_keyserver }}"
    id: "{{ clickhouse_deb_keyid }}"
    state: present

- name: CLICKHOUSE | Add clickhouse apt repository (deb)
  apt_repository:
    repo: "{{ clickhouse_deb_repo }}"
    state: present

- name: CLICKHOUSE | Be sure clickhouse packages are installed (apt)
  apt:
    name: "{{ clickhouse_packages }}"
    state: present
    update_cache: true

- name: CLICKHOUSE | Ensure base directory exist
  file:
    state: directory
    dest: "{{ clickhouse_base_path }}"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "{{ clickhouse_base_directory_mode }}"
  become: true

- name: CLICKHOUSE | Ensure user files and access control directories exist
  file:
    state: directory
    dest: "{{ item }}"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: 0750
  with_items:
    - "{{ clickhouse_access_control_directory }}"
    - "{{ clickhouse_user_files_directory }}"
  become: true

- name: CLICKHOUSE | Ensure needed config directories exist
  file:
    state: directory
    dest: "{{ item }}"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "{{ clickhouse_config_directory_mode }}"
  with_items:
    - "{{ clickhouse_config_directory }}"
    - "{{ clickhouse_config_directory_config_d }}"
    - "{{ clickhouse_config_directory_users_d }}"
  become: true

- name: CLICKHOUSE | Ensure needed tmp directories exist
  file:
    state: directory
    dest: "{{ clickhouse_tmp_directory }}"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "{{ clickhouse_tmp_directory_mode }}"
  become: true

- name: CLICKHOUSE | Ensure needed log directory exist
  file:
    state: directory
    dest: "{{ clickhouse_log_directory }}"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "{{ clickhouse_log_directory_mode }}"
  become: true
