---

- name: CLICKHOUSE | Install
  include_tasks: "install-{{ ansible_distribution }}.yml"
  tags:
    - clickhouse_install

- name: CLICKHOUSE | Configure clickhouse
  include_tasks: config-clickhouse.yml
  tags:
    - clickhouse_configure

- name: CLICKHOUSE | Service
  include_tasks: service-clickhouse.yml
  tags:
    - clickhouse_service

- name: CLICKHOUSE | Configure databases
  include_tasks: config-databases.yml
  tags:
    - clickhouse_configure
