---

- name: CLICKHOUSE | Install
  include_tasks: "install-{{ ansible_distribution }}.yml"
  tags:
    - clickhouse_install

- name: CLICKHOUSE | Configure clickhouse
  include_tasks: config/clickhouse.yml
  tags:
    - clickhouse_configure

- name: CLICKHOUSE | Configure copier
  include_tasks: config/copier.yml
  tags:
    - clickhouse_configure_copier

- name: CLICKHOUSE | Service
  include_tasks: service-clickhouse.yml
  tags:
    - clickhouse_service

- name: CLICKHOUSE | Configure settings profiles
  include_tasks: config/settings-profiles.yml
  tags:
    - clickhouse_settings_profiles
  when: clickhouse_role_manage_settings_profiles

- name: CLICKHOUSE | Configure roles
  include_tasks: config/roles.yml
  tags:
    - clickhouse_roles
  when: clickhouse_role_manage_roles

- name: CLICKHOUSE | Configure quotas
  include_tasks: config/quotas.yml
  tags:
    - clickhouse_quotas
  when: clickhouse_role_manage_quotas

- name: CLICKHOUSE | Configure users
  include_tasks: config/users.yml
  tags:
    - clickhouse_users
  when: clickhouse_role_manage_users

- name: CLICKHOUSE | Configure databases
  include_tasks: config/databases.yml
  tags:
    - clickhouse_databases
  when: clickhouse_role_manage_databases

- name: CLICKHOUSE | Configure perms & privs
  include_tasks: config/perms_and_privs.yml
  tags:
    - clickhouse_grants
  when: clickhouse_role_manage_grants
