---

- name: CLICKHOUSE | Copy systemd unit configuration file
  template:
    src: "{{ clickhouse_service_template_path }}"
    dest: "/etc/systemd/system/{{ clickhouse_service }}.service"
    mode: 0644
    owner: root
    group: root
  notify: reload-clickhouse

- name: CLICKHOUSE | Configuring service
  systemd:
    name: "{{ clickhouse_service }}"
    state: "{{ clickhouse_service_state }}"
    enabled: "{{ clickhouse_service_enabled }}"
    daemon_reload: yes
