---

- name: CLICKHOUSE | Remove file (delete file if exists)
  file:
    path: "/etc/systemd/system/{{ clickhouse_service }}.service"
    state: absent

- name: CLICKHOUSE | Configuring service
  systemd:
    name: "{{ clickhouse_service }}"
    state: "{{ clickhouse_service_state }}"
    enabled: "{{ clickhouse_service_enabled }}"
    daemon_reload: yes

- name: CLICKHOUSE | Wait for service listening
  wait_for:
    host: localhost
    port: "{{ clickhouse_http_port }}"
    state: "{{ clickhouse_service_state }}"
    delay: 5
    timeout: 300
  when:
    - clickhouse_service_enabled
    - clickhouse_service_state == "started"

- name: CLICKHOUSE | Copy Clickhouse JDBC Bridge service
  template:
    src: "{{ clickhouse_jdbc_bridge_service_template_path }}"
    dest: "/etc/systemd/system/{{ clickhouse_jdbc_bridge_service }}.service"
    mode: 0644
    owner: root
    group: root
  notify: reload-clickhouse
  when: clickhouse_jdbc_bridge is defined

- name: CLICKHOUSE | Configuring Clickhouse JDBC Bridge service
  systemd:
    name: "{{ clickhouse_jdbc_bridge_service }}"
    state: "{{ clickhouse_jdbc_bridge_service_state }}"
    enabled: "{{ clickhouse_jdbc_bridge_service_enabled }}"
    daemon_reload: yes
  when: clickhouse_jdbc_bridge is defined
