---

# Clickhouse role management
clickhouse_install_db: True
clickhouse_role_manage_users: True
clickhouse_role_manage_roles: True
clickhouse_role_manage_databases: True
clickhouse_role_manage_settings_profiles: True
clickhouse_role_manage_quotas: True
clickhouse_role_manage_grants: True

clickhouse_private_tmp: false

clickhouse_custom_extra_config_file_path: "{{ playbook_dir }}/config_files/config/config.d"
clickhouse_custom_extra_users_file_path: "{{ playbook_dir }}/config_files/users/users.d"

# Users
clickhouse_admin_user: admin
clickhouse_admin_password: admin

clickhouse_admin_users:
  - user:
    name: "{{ clickhouse_admin_user }}"
    password: "{{ clickhouse_admin_password }}"
    networks: "{{ clickhouse_default_networks }}"
    profile: "default"
    quota: "default"
    access_management: 1

clickhouse_custom_users_xml:
  - user:
    name: "Bunta"
    password: "TofuShop"
    networks: "{{ clickhouse_default_networks }}"
    profile: "default"
    quota: "default"
    databases: [ex_racing]

clickhouse_custom_users:
  - user:
    name: "Takumi"
    password_type: PLAINTEXT_PASSWORD
    password: "AE86"
    networks:
      - "IP '::/0'"
    settings:
      - "max_memory_usage = 10000000000"
    role:
      - projectd_members
      - tofu_shop
    profile:
      - default
    grantees:
      - projectd_members
    quota: "default"
    databases: [ProjectD]
  - user:
    name: "Iketani"
    password_type: PLAINTEXT_PASSWORD
    password: "S13"
    networks:
      - "IP '::/0'"
  - user:
    name: "Ryosuke"
    password_type: PLAINTEXT_PASSWORD
    password: "PjD4ever"
    networks:
      - "IP '::/0'"
    databases: [ProjectD]
    grantees:
      - projectd_members
      - -tofu_shop
    profile:
      - default
      - max_memory_usage_profile
#     ldap_server: adf.com
#     kerberos: ""

# Roles
clickhouse_custom_roles:
  - role:
    name: projectd_members
    settings:
      - "max_memory_usage = 10000000000"
  - role:
    name: tofu_shop
    settings:
      - "max_memory_usage = 100"
  - role:
    name: initial_d

clickhouse_custom_grants:
  - on:
    databases: [Akina]
    tables: ["*"]
    privileges: [SELECT]
    to: [initial_d]
  - on:
    # cluster:
    databases: ["racing"]
    tables: ["*"]
    # columns: ["*"]
    privileges: [ALL]
    to: [Takumi, Iketani]
  - on:
    # cluster:
    databases: ["Akina"]
    tables: [calendar, records]
    # columns: [Notes]
    privileges: [ALL]
    to: [Takumi, Iketani]
    with_grant_option: True
  - on:
    # cluster:
    databases: ["Akina"]
    tables: [records]
    privileges: [SELECT, UPDATE]
    to: [Iketani]
    with_grant_option: False

clickhouse_custom_grant_roles:
  - roles: [initial_d]
    to: [Takumi, Iketani]
    # cluster:

# Settings profiles
clickhouse_custom_settings_profiles:
  - profile:
    name: max_memory_usage_profile
    settings:
      - max_memory_usage = 100000001

# Quotas
clickhouse_custom_quotas:
  - quota:
    name: example_quota
    # keyed: ip_address  # One of this: user_name | ip_address | client_key | client_key,user_name | client_key,ip_address | NOT KEYED
    settings:
      - "INTERVAL 30 minute MAX execution_time = 0.5"
    to:  # Use a minus to use ALL EXCEPT e.g: -test_role
      - tofu_shop
  - quota:
    name: example_quota_except
    keyed: NOT KEYED
    settings:
      - "INTERVAL 300 minute MAX execution_time = 0.5"
    to:
      - -tofu_shop

# Databases
clickhouse_custom_databases:
  - name: ProjectD
    engine: Atomic
    comment: PjD_data
  - name: racing
  - name: ex_racing

# Configuration
clickhouse_listen_hosts:
  - 0.0.0.0

clickhouse_default_networks:
  - '::/0'

clickhouse_macros:
  - macro: |
      <shard>1</shard>
      <replica>1</replica>
    server:
      - clickhouse
  - macro: |
      <db_default>default</db_default>

# Copier Configuration
clickhouse_copier_logger_level: information
clickhouse_copier_logger_log: /var/log/clickhouse-server/clickhouse-copier.log
clickhouse_copier_logger_errorlog: /var/log/clickhouse-server/clickhouse-copier.err.log
clickhouse_copier_logger_size: 1000M
clickhouse_copier_logger_count: 10
clickhouse_zookeeper:
  - node:
    host: zookeeper-test1
    port: 2181
  - node:
    host: zookeeper-test2
    port: 2181
  - node:
    host: zookeeper-test3
    port: 2181

# JDBC Bridge
clickhouse_jdbc_bridge_service: clickhouse-jdbc-bridge
clickhouse_jdbc_bridge_user: "{{ clickhouse_user }}"
clickhouse_jdbc_bridge_group: "{{ clickhouse_group }}"
clickhouse_jdbc_bridge_service_template_path: jdbc-bridge/clickhouse-jdbc-bridge.service.j2
clickhouse_jdbc_bridge_service_state: started
clickhouse_jdbc_bridge_service_enabled: True
clickhouse_jdbc_bridge_config_path: "/etc/clickhouse-jdbc-bridge"
clickhouse_jdbc_bridge_file_drivers_path: "{{ playbook_dir }}/files/jdbc-drivers"
clickhouse_jdbc_bridge_drivers_path: "{{ clickhouse_base_path }}/drivers/"
clickhouse_jdbc_bridge_documentation_link: "https://github.com/ClickHouse/clickhouse-jdbc-bridge/blob/v{{ clickhouse_jdbc_bridge_version }}/README.md"
clickhouse_jdbc_bridge_log_path: /var/log/clickhouse-jdbc-bridge
clickhouse_jdbc_bridge_log_file: "{{ clickhouse_jdbc_bridge_log_path }}/clickhouse-jdbc-bridge.log"
clickhouse_jdbc_bridge_log_level: DEBUG
clickhouse_jdbc_bridge_env: |
  JVM_ARGS="-Xms1024m -Xmx2048m"
clickhouse_jdbc_bridge_version: 2.1.0
clickhouse_jdbc_bridge_deb_package: "https://github.com/ClickHouse/clickhouse-jdbc-bridge/releases/download/v{{ clickhouse_jdbc_bridge_version }}/clickhouse-jdbc-bridge_{{ clickhouse_jdbc_bridge_version }}-1_all.deb"
# clickhouse_jdbc_bridge_rpm_package: "https://github.com/ClickHouse/clickhouse-jdbc-bridge/releases/download/v{{ clickhouse_jdbc_bridge_version }}/clickhouse-jdbc-bridge-{{ clickhouse_jdbc_bridge_version }}-1.noarch.rpm"
clickhouse_jdbc_bridge:
  host: 127.0.0.1
  port: 9019
clickhouse_jdbc_bridge_datasources_path: "{{ clickhouse_jdbc_bridge_config_path }}/config/datasources"
clickhouse_jdbc_bridge_datasources:
  - name: clickhouse_test
    datasource:
      $schema: "../datasource.jschema"
      clickhouse:
        driverUrls: ["https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.3.2-patch8/clickhouse-jdbc-0.3.2-patch8-http.jar"]
        driverClassName: "com.clickhouse.jdbc.ClickHouseDriver"
        jdbcUrl: "jdbc:clickhouse://localhost:8123/system?compress=false"
        username: "{{ clickhouse_admin_user }}"
        password: "{{ clickhouse_admin_password }}"
