---

# Version
clickhouse_version: 22.8.8.3
clickhouse_release_type: lts

# Clickhouse role management
clickhouse_role_manage_users: True
clickhouse_role_manage_roles: True
clickhouse_role_manage_databases: True
clickhouse_role_manage_settings_profiles: True
clickhouse_role_manage_quotas: True
clickhouse_role_manage_grants: True

# clickhouse_custom_config_file_path: "{{ playbook_dir }}/config_files/config"
# clickhouse_custom_users_file_path: "{{ playbook_dir }}/config_files/users"

# Users
clickhouse_admin_user: admin
clickhouse_admin_password: admin

clickhouse_admin_users:
  - user:
    name: "{{ clickhouse_admin_user }}"
    password: "{{ clickhouse_admin_password }}"
    networks: "{{ clickhouse_default_networks }}"
    profile: "default"
    quota: "default"
    access_management: 1

clickhouse_custom_users_xml:
  - user:
    name: "Bunta"
    password: "TofuShop"
    networks: "{{ clickhouse_default_networks }}"
    profile: "default"
    quota: "default"
    databases: [ex_racing]

clickhouse_custom_users:
  - user:
    name: "Takumi"
    password_type: PLAINTEXT_PASSWORD
    password: "AE86"
    networks:
      - "IP '::/0'"
    settings:
      - "max_memory_usage = 10000000000"
    role:
      - projectd_members
      - tofu_shop
    profile:
      - default
    grantees:
      - projectd_members
    quota: "default"
    databases: [ProjectD]
  - user:
    name: "Iketani"
    password_type: PLAINTEXT_PASSWORD
    password: "S13"
    networks:
      - "IP '::/0'"
  - user:
    name: "Ryosuke"
    password_type: PLAINTEXT_PASSWORD
    password: "PjD4ever"
    networks:
      - "IP '::/0'"
    databases: [ProjectD]
    grantees:
      - projectd_members
      - -tofu_shop
    profile:
      - default
      - max_memory_usage_profile
#     ldap_server: adf.com
#     kerberos: ""

# Roles
clickhouse_custom_roles:
  - role:
    name: projectd_members
    settings:
      - "max_memory_usage = 10000000000"
  - role:
    name: tofu_shop
    settings:
      - "max_memory_usage = 100"
  - role:
    name: initial_d

clickhouse_custom_grants:
  - on:
    databases: [Akina]
    tables: ["*"]
    privileges: [SELECT]
    to: [initial_d]
  - on:
    # cluster:
    databases: ["racing"]
    tables: ["*"]
    # columns: ["*"]
    privileges: [ALL]
    to: [Takumi, Iketani]
  - on:
    # cluster:
    databases: ["Akina"]
    tables: [calendar, records]
    # columns: [Notes]
    privileges: [ALL]
    to: [Takumi, Iketani]
    with_grant_option: True
  - on:
    # cluster:
    databases: ["Akina"]
    tables: [records]
    privileges: [SELECT, UPDATE]
    to: [Iketani]
    with_grant_option: False

clickhouse_custom_grant_roles:
  - roles: [initial_d]
    to: [Takumi, Iketani]
    # cluster:

# Settings profiles
clickhouse_custom_settings_profiles:
  - profile:
    name: max_memory_usage_profile
    settings:
      - max_memory_usage = 100000001

# Quotas
clickhouse_custom_quotas:
  - quota:
    name: example_quota
    # keyed: ip_address  # One of this: user_name | ip_address | client_key | client_key,user_name | client_key,ip_address | NOT KEYED
    settings:
      - "INTERVAL 30 minute MAX execution_time = 0.5"
    to:  # Use a minus to use ALL EXCEPT e.g: -test_role
      - tofu_shop
  - quota:
    name: example_quota_except
    keyed: NOT KEYED
    settings:
      - "INTERVAL 300 minute MAX execution_time = 0.5"
    to:
      - -tofu_shop

# Databases
clickhouse_custom_databases:
  - name: ProjectD
    engine: Atomic
    comment: PjD_data
  - name: racing
  - name: ex_racing

# Configuration
clickhouse_listen_hosts:
  - 0.0.0.0

clickhouse_default_networks:
  - '::/0'

clickhouse_macros:
  - macro: |
      <shard>1</shard>
      <replica>1</replica>
    server:
      - clickhouse
  - macro: |
      <db_default>default</db_default>

# Copier Configuration
clickhouse_copier_logger_level: information
clickhouse_copier_logger_log: /var/log/clickhouse-server/clickhouse-copier.log
clickhouse_copier_logger_errorlog: /var/log/clickhouse-server/clickhouse-copier.err.log
clickhouse_copier_logger_size: 1000M
clickhouse_copier_logger_count: 10
clickhouse_zookeeper:
  - node:
    host: zookeeper-test1
    port: 2181
  - node:
    host: zookeeper-test2
    port: 2181
  - node:
    host: zookeeper-test3
    port: 2181
