---

- name: CLICKHOUSE | Previous grants cleaning (Optional step)
  command: "clickhouse-client -u {{ clickhouse_admin_user }} --password {{ clickhouse_admin_password }} -q \"
    REVOKE ALL ON *.* FROM ALL EXCEPT {{ (clickhouse_default_users + clickhouse_admin_users + clickhouse_custom_users_xml) | map(attribute='name') | join(', ') }};
    \""
  changed_when: False
  when: clickhouse_custom_grants_previous_cleanup
  no_log: True
  tags:
    - clickhouse_grants
    - select
    - SQL_driven

- name: CLICKHOUSE | Grant perms & privs
  include_tasks: config/grants.yml
  with_items: "{{ clickhouse_custom_grants }}"
  when: clickhouse_custom_grants is defined
  tags:
    - clickhouse_grants

- name: CLICKHOUSE | Grant roles
  include_tasks: config/grants-roles.yml
  with_items: "{{ clickhouse_custom_grant_roles }}"
  when: clickhouse_custom_grant_roles is defined
  tags:
    - clickhouse_grants
