---

- name: Restart-clickhouse
  systemd:
    name: "{{ clickhouse_service }}"
    state: restarted

- name: Reload-clickhouse
  systemd:
    name: "{{ clickhouse_service }}"
    state: reloaded

- name: Restart-clickhouse-JDBC-bridge
  systemd:
    name: "{{ clickhouse_jdbc_bridge_service }}"
    state: restarted
  when: clickhouse_jdbc_bridge is defined

- name: Reload-clickhouse-JDBC-bridge
  systemd:
    name: "{{ clickhouse_jdbc_bridge_service }}"
    state: reloaded
  when: clickhouse_jdbc_bridge is defined
