---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: clickhouse
    groups:
      - clickhouse_group
    image: ${MOLECULE_DISTRO:-debian:bullseye-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    command: ${MOLECULE_DOCKER_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    stop_signal: 'RTMIN+3'
    exposed_ports:
      - 8123/tcp
      - 9000/tcp
      - 9019/tcp
    published_ports:
      - 0.0.0.0:8123:8123/tcp
      - 0.0.0.0:9000:9000/tcp
      - 0.0.0.0:9019:9019/tcp

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: True
  options:
    vvv: True

scenario:
  name: default

verifier:
  name: ansible
