---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: clickhouse
    groups:
      - clickhouse_group
    image: ${MOLECULE_DISTRO:-debian:bullseye-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/home/david/Desktop/ch:/var/lib/clickhouse/'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    exposed_ports:
      - 8123/tcp
      - 9000/tcp
    published_ports:
      - 0.0.0.0:8123:8123/tcp
      - 0.0.0.0:9000:9000/tcp
    dns_servers:
      - 10.80.1.86
      - 10.80.5.61
      - 10.80.11.5

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: ansible
