---

- name: CLICKHOUSE | Copy systemd unit configuration file
  ansible.builtin.template:
    src: "{{ clickhouse_service_template_path }}"
    dest: "/etc/systemd/system/{{ clickhouse_service }}.service"
    mode: 0644
    owner: root
    group: root
  notify: Reload-clickhouse

- name: CLICKHOUSE | Configuring service
  ansible.builtin.systemd:
    name: "{{ clickhouse_service }}"
    state: "{{ clickhouse_service_state }}"
    enabled: "{{ clickhouse_service_enabled }}"
    daemon_reload: yes

- name: CLICKHOUSE | Wait for service listening
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ clickhouse_http_port }}"
    state: "{{ clickhouse_service_state }}"
    delay: 5
    timeout: 300
  when:
    - clickhouse_service_enabled
    - clickhouse_service_state == "started"
